title: Just the Notes
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://engops.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
#remote_theme: jekyll-theme-midnight
search_enabled: true
plugins:
  - jekyll-feed

#aux_links:
#    "":
#      - ""
